blogger/urls.py
from django.urls import path, re_path
from . import views

app_name = "blogger"

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    path('post/tmp/<int:pk>/', views.tmpDetail, name='tmpDetail'),
    path('post/<int:post_id>/', views.detail, name='detail'),
    path('post/<int:post_id>/submitComment', views.addComment,
         name='addComment'),
    path('tmp', views.tmpDetail, name='tmpDetail'),
]

grace_bday/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

llu_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('for_grace/', include('grace_bday.urls')),
    path('blog/', include('blogger.urls')),
]

blogger/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Tag(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    abstract = models.CharField(max_length=500, blank=True)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    is_hidden = models.BooleanField(default=False)
    allow_comment = models.BooleanField(default=True)

    def __str__(self):
        shortTitle = self.title[:40] + "..." if len(self.title) > 40 else self.title
        return shortTitle


class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.CharField(max_length=20)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        shortContent = self.content[:40] + "..." if len(self.content) > 40 else self.content
        return shortContent

blogger/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Tag, Category
from .form import CommentForm

# Create your views here.


def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    tag_list = Tag.objects.all()
    category_list = Category.objects.all()
    return render(
        request,
        'blogger/index.html',
        context={
            'post_list': post_list,
            'tag_list': tag_list,
            'category_list': category_list
        })


def tmpDetail(request, pk=None):
    return render(request, 'blogger/single_new.html')


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_list = post.comment_set.filter(is_approved=True).order_by('-created_time')
    form = CommentForm()
    return render(
        request,
        'blogger/detail.html',
        context={
            'post': post,
            'form': form,
            'comment_list': comment_list
        })


def addComment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_list = post.comment_set.filter(is_approved=True).order_by('-created_time')
            context = {
                'post': post,
                'form': form,
                'comment_list': comment_list
            }
            return render(request, 'blogger/detail.html', context)

    return redirect('blogger:detail', post_id=post_id)

grace_bday/views.py
from django.shortcuts import render
from datetime import datetime

# Create your views here.

def index(request):
    htmlTemplate = 'grace_bday/index.html'
    # Use UTC time
    expectedDate = datetime(2018, 1, 28, 0, 0)
    now = datetime.now()
    if now > expectedDate:
        htmlTemplate = 'grace_bday/index_new.html'
    return render(request, htmlTemplate)

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

blogger/templates/blogger/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
  <head>

    <!--- Basic Page Needs
	================================================== -->
    <meta charset="utf-8">
    <title>Linkui gets luck</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
	 ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
	 ================================================== -->
    <link rel="stylesheet" href="{% static "blogger/css/default.css" %}">
    <link rel="stylesheet" href="{% static "blogger/css/layout.css" %}">
    <link rel="stylesheet" href="{% static "blogger/css/media-queries.css" %}">

    <!-- Script
	 ================================================== -->
    <script src="{% static "blogger/js/modernizr.js" %}"></script>

    <!-- Favicons
	 ================================================== -->
    <link rel="shortcut icon" href="{% static "blogger/favicon.png" %}" >

  </head>

  <body>

    <!-- Header
	 ================================================== -->
    <header id="top">

      <div class="row">

   	<div class="header-content twelve columns">

	  <h1 id="logo-text"><a href="{% url 'blogger:index' %}" title="">Linkui gets luck</a></h1>
	  <p id="intro">当你决定出发，最大的困难已不复存在!</p>

	</div>			

      </div>

      <nav id="nav-wrap"> 

	<a class="mobile-btn" href="#nav-wrap" title="Show navigation">Show Menu</a>
	<a class="mobile-btn" href="#" title="Hide navigation">Hide Menu</a>

	<div class="row">    		            

	  <ul id="nav" class="nav">
	    <li class="current"><a href="{% url 'blogger:index' %}">Home</a></li>
	    <li class="has-children"><a href="#">Dropdown</a>
	      <ul>
	        <li><a href="#">Submenu 01</a></li>
	        <li><a href="#">Submenu 02</a></li>
	        <li><a href="#">Submenu 03</a></li>
	      </ul>
	    </li>
	    <li><a href="demo.html">Demo</a></li>	
	    <li><a href="archives.html">Archives</a></li>
	    <li class="has-children"><a href="single.html">Blog</a>
	      <ul>
	        <li><a href="blog.html">Blog Entries</a></li>
	        <li><a href="single.html">Single Blog</a></li>	                     
	      </ul>
	    </li>		      	
	    <li><a href="/admin">Admin</a></li>
	  </ul> <!-- end #nav -->			   	 

	</div> 

      </nav> <!-- end #nav-wrap --> 	     

    </header> <!-- Header End -->

    <!-- Content
	 ================================================== -->
    <div id="content-wrap">

      <div class="row">

	{% block content %}{% endblock %}

      </div> <!-- end row -->

    </div> <!-- end content-wrap -->
    

    <!-- Footer
	 ================================================== -->
    <footer>

      <div class="row"> 

      	<!--<div class="twelve columns">	
	    <ul class="social-links">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>               
              <li><a href="#"><i class="fa fa-github-square"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              <li><a href="#"><i class="fa fa-flickr"></i></a></li>               
              <li><a href="#"><i class="fa fa-skype"></i></a></li>
            </ul>			
      	</div>-->
      	
        <div class="ten columns info">

          <h3>About myself</h3>

          <p>About two years ago, I switched my major programming language from Java to Python, and as a software
            quality engineer, my daily work is to write testing framework code and testing scripts with Python.
            As I get addicted in the attraction of Python, I decided to get myself familiar with the web development
            to keep up with this "information system oriented" age, And Aha! Here is my blog site developed by myself to share
            interesting things with people all over the world.
          </p>

          <p>Thanks Django team for providing such a powerful Python web framework, and thanks Google for providing
            reliable cloud service at low cost!</p>

        </div>

        <!--<div class="four columns">

            <h3>Photostream</h3>
            
            <ul class="photostream group">
              <li><a href="#"><img alt="thumbnail" src="{% static "blogger/images/thumb.jpg" %}"></a></li>
              <li><a href="#"><img alt="thumbnail" src="{% static "blogger/images/thumb.jpg" %}"></a></li>
              <li><a href="#"><img alt="thumbnail" src="{% static "blogger/images/thumb.jpg" %}"></a></li>
              <li><a href="#"><img alt="thumbnail" src="{% static "blogger/images/thumb.jpg" %}"></a></li>
              <li><a href="#"><img alt="thumbnail" src="{% static "blogger/images/thumb.jpg" %}"></a></li>
              <li><a href="#"><img alt="thumbnail" src="{% static "blogger/images/thumb.jpg" %}"></a></li>
              <li><a href="#"><img alt="thumbnail" src="{% static "blogger/images/thumb.jpg" %}"></a></li>
              <li><a href="#"><img alt="thumbnail" src="{% static "blogger/images/thumb.jpg" %}"></a></li>
            </ul>

        </div>-->

        <div class="two columns">
          <h3 class="social">Navigate</h3>

          <ul class="navigate group">
            <li><a href="#">Home</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Demo</a></li>
            <li><a href="#">Archives</a></li>
            <li><a href="#">About</a></li>
          </ul>
        </div>

        <p class="copyright">&copy; Copyright 2018 Linkui Lu.<br>Frontend designed by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>.</p>
        
      </div> <!-- End row -->

      <div id="go-top"><a class="smoothscroll" title="Back to Top" href="#top"><i class="fa fa-chevron-up"></i></a></div>

    </footer> <!-- End Footer-->


    <!-- Java Script
	 ================================================== -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "blogger/js/jquery-1.10.2.min.js" %}"><\/script>')</script>
      <script type="text/javascript" src="{% static "blogger/js/jquery-migrate-1.2.1.min.js" %}"></script>
      <script src="{% static "blogger/js/main.js" %}"></script>

  </body>

</html>

blogger/templates/blogger/detail.html
{% extends "blogger/base.html" %}
{% load static %}
{% block content %}
<div id="main" class="twelve columns">
    <article class="entry">

        <header class="entry-header">

            <h2 class="entry-title">{{ post.title }}</h2>

            <div class="entry-meta">
                <ul>
                    <li>{{ post.created_time }}</li>
                    <span class="meta-sep">&bull;</span>
                    <li>
                        <a href="#" title="" rel="category tag">{{ post.category }}</a>
                    </li>
                    <span class="meta-sep">&bull;</span>
                    <li>{{ post.author.first_name }}</li>
                </ul>
            </div>

        </header>
        <!--
        <div class="entry-content-media">
          <div class="post-thumb">
            <img src="{% static "blogger/images/m-farmerboy.jpg" %}">
          </div>
        </div>
        -->
        <div class="entry-content">
            <p class="lead"><i>{{ post.abstract }}</i></p>

            <div>{{ post.content|safe }}</div>
        </div>

        <p class="tags">
            <span>Tagged in: </span>
            {% if post.tags.all %}
            {% for tag in post.tags.all %}
            <a href="#">{{ tag.name }}</a>,
            {% endfor %}
            {% else %}
            <span>no tag is attached to this post.</span>
            {% endif %}
        </p>

        <ul class="post-nav group">
            <li class="prev"><a rel="prev" href="#"><strong>Previous Article</strong>To be implemented...</a></li>
            <li class="next"><a rel="next" href="#"><strong>Next Article</strong>To be implemented...</a></li>
        </ul>

    </article>

    <!-- Comments
         ================================================== -->
    <div id="comments">

        <!-- commentlist -->
        <ol class="commentlist">

            {% if comment_list %}
            <h3>{{ comment_list|length }} Comments</h3>
            {% for comment in comment_list %}
            <li class="depth-1">
                <div class="avatar">
                    <img width="50" height="50" class="avatar" src="{% static " blogger/images/user-01.png" %}" alt="">
                </div>

                <div class="comment-content">

                    <div class="comment-info">
                        <cite>{{ comment.author }}</cite>

                        <div class="comment-meta">
                            <time class="comment-time" datetime="2014-07-12T23:05">{{ comment.created_time }}
                            </time>
                            <!--
                          <span class="sep">/
                          </span>
                          <a class="reply" href="#">Reply
                          </a>
                          -->
                        </div>
                    </div>

                    <div class="comment-text">
                        <p>{{ comment.content }}
                        </p>
                    </div>

                </div>
            </li>
            {% endfor %}
            {% else %}
            <h3>No comment is submitted for this post!</h3>
            {% endif %}

        </ol> <!-- Commentlist End -->
        <!-- respond -->
        <div class="respond">
            {% if post.allow_comment %}
            <h3>Leave a Comment</h3>
            <p>Comment submitted will be displayed after it is approved.</p>

            <!-- form -->
            <form name="contactForm" id="contactForm" method="post" action="submitComment">
                {% csrf_token %}
                <fieldset>
                    <div class="group">
                        <label for="{{ form.author.id_for_label }}">Name <span class="required">*</span></label>
                        {{ form.author }}
                        {{ form.author.errors }}
                    </div>
                    <div class="group">
                        <label for="{{ form.content.id_for_label }}">Message <span class="required">*</span></label>
                        {{ form.content }}
                        {{ form.content.errors }}
                    </div>
                    <button type="submit" class="submit">Submit</button>

                    <!--
                    <div class="group">
                        <label for="cName">Name <span class="required">*</span></label>
                        <input name="cName" type="text" id="cName" size="35" value=""/>
                    </div>

                  <div class="group">
                    <label for="cEmail">Email <span class="required">*</span></label>
                    <input name="cEmail" type="text" id="cEmail" size="35" value="" />
                  </div>

                  <div class="group">
                    <label for="cWebsite">Website</label>
                    <input name="cWebsite" type="text" id="cWebsite" size="35" value="" />
                  </div>

                    <div class="group">
                        <label for="cMessage">Message <span class="required">*</span></label>
                        <textarea name="cMessage" id="cMessage" rows="10" cols="20"></textarea>
                    </div>
                    -->
                </fieldset>
            </form> <!-- Form End -->

        </div> <!-- Respond End -->
        {% else %}
        <h3>Comment is not allowed for this post.</h3>
        {% endif %}

    </div>  <!-- Comments End -->
</div>
{% endblock %}

blogger/templates/blogger/index.html
{% extends "blogger/base.html" %}
{% block content %}
<div id="main" class="eight columns">
  {% for post in post_list %}
  <article class="entry">

    <header class="entry-header">

      <h2 class="entry-title">
	<a href="{% url 'blogger:detail' post.id %}" title="">{{ post.title }}</a>
      </h2>
      
      <div class="entry-meta">
	<ul>
	  <li>{{ post.created_time }}</li>
	  <span class="meta-sep">&bull;</span>								
	  <li><a href="#" rel="category tag">{{ post.category }}</a></li>
	  <span class="meta-sep">&bull;</span>
	  <li>{{ post.author.first_name }}</li>
	</ul>
      </div> 
      
    </header> 
    
    <div class="entry-content">
      {% if post.abstract %}
      <p>{{ post.abstract }}</p>
      {% else %}
      <p>{{ post.content|safe }}</p>
      {% endif %}
    </div> 

  </article> <!-- end article -->
  {% empty %}
  <h2 class="entry-title">Oops! no post has been created!</h2>

  {% endfor %}
</div>
{% include "blogger/base_sidebar.html" %}
{% endblock %}

grace_bday/templates/grace_bday/index.html
{% load static %}

<!DOCTYPE html>
<html>

<link rel="stylesheet" type="text/css" href="{% static 'grace_bday/css/style.css' %}" />

<body>

<div class="bgimg">
  <div class="topleft">
    <p>Feast on Jan 27 2018 at 07:30pm CST</p>
  </div>
  <div class="middle">
    <!--<h1>Celebrating 18 year old birthday for Grace!</h1>-->
    <p class="center_text">Celebrating 18 year old birthday for Grace!</p>
    <hr>
    <p class="counter" id="demo"></p>
  </div>
</div>

<script src="{% static 'grace_bday/js/countdown.js' %}"></script>

</body>
</html>

grace_bday/templates/grace_bday/index2.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Countdown Timer</title>
    <style>
      #wrapper {
      text-align:center;
      border:1px solid #7F7F7F;
      width:150px;
      margin:25px auto;
      padding:25px;
      background-color:#E3E4E4;
      }
      #myTimer {
      font:64px Tahoma bold;
      padding:20px;
      display:block;
      }
      button {
      width:125px;
      padding:10px;
      }
      .btnEnable {
      background-color:#E6F9D2;
      border:1px solid #97DE4C;
      color:#232323;
      cursor:pointer;
      }
      .btnDisable {
      background-color:#FCBABA;
      border:1px solid #DD3939;
      color:#232323;
      cursor:wait;
      }
    </style>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  </head>
  <body>
    <div id="wrapper">
      <div id="myTimer"></div>
      <button type="button" id="myBtn" class="btnDisable" disabled onclick="alert('Finally!')">Please wait...</button>
    </div>
    <script>
      var sec = 15;
      var myTimer = document.getElementById('myTimer');
      var myBtn = document.getElementById('myBtn');
      window.onload = countDown;

      function countDown() {
      if (sec < 10) {
		myTimer.innerHTML = "0" + sec;
		} else {
		myTimer.innerHTML = sec;
		}
		if (sec <= 0) {
			   $("#myBtn").removeAttr("disabled");
			   $("#myBtn").removeClass().addClass("btnEnable");
			   $("#myTimer").fadeTo(2500, 0);
			   myBtn.innerHTML = "Click Me!";
			   return;
			   }
			   sec -= 1;
			   window.setTimeout(countDown, 1000);
			   }
			   </script>
  </body>
</html>

grace_bday/templates/grace_bday/index_new.html
{% load static %}

<!DOCTYPE html>
<html>

<link rel="stylesheet" type="text/css" href="{% static 'grace_bday/css/style.css' %}" />
<!--<link rel="stylesheet" type="text/css" href="style.css"/>-->
<link rel="stylesheet" type="text/css" href="{% static 'grace_bday/css/button_style.css' %}" />
<!--<link href='button_style.css' rel='stylesheet' type='text/css'>-->

<body>

<div class="bgimg">
  <div class="topleft">
    <p>Feast on Jan 27 2018 at 07:30pm CST</p>
  </div>
  <div class="middle">
    <!--<h1>Celebrating 18 year old birthday for Grace!</h1>-->
    <p class="center_text">Celebrating 18 year old birthday for Grace!</p>
    <hr>
    <p class="counter" id="demo"></p>
  </div>
</div>

<div class="middlelower">
  <a href="http://posts.careerengine.us/p/580709d2c1e4b801b8bcc70d" class="btn">
  <svg>
    <defs>
        <linearGradient id="grad1">
            <stop offset="0%" stop-color="#f7f388"/>
            <stop offset="100%" stop-color="#f788ef" />
        </linearGradient>
    </defs>
     <rect x="5" y="5" rx="25" fill="none" stroke="url(#grad1)" width="266" height="50"></rect>
  </svg>
  <span>Explore the feast</span>
</a>
</div>

<script src="{% static 'grace_bday/js/countdown.js' %}"></script>
<!--<script src="js/countdown.js"></script>-->

</body>
</html>

grace_bday/templates/grace_bday/menu_site/index-1.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Menu</title>
<meta charset="utf-8">
<meta name = "format-detection" content = "telephone=no" />
<link rel="icon" href="images/favicon.ico">
<link rel="shortcut icon" href="images/favicon.ico" />
<link rel="stylesheet" href="css/stuck.css">
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/touchTouch.css">
</head>

<body>

<!--=====================
          Content
======================-->
<section class="content gallery pad1"><div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
  <div class="container">
    <div class="row">
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/bbig1.jpg" class="gall_item"><img src="images/page2_img1.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Vivamus at magna non nunc </a></div>
            Rehoncus. Aliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laoreet 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/big3.jpg" class="gall_item"><img src="images/page2_img2.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Divamus at magna non nunce </a></div>
            Kehoncus. Aliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laoreet 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/bbig3.jpg" class="gall_item"><img src="images/page2_img3.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Livamus at magna non nunc </a></div>
            Tehoncus. Aliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laoreeto 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
      <div class="clear sep__1"></div>
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/bbig4.jpg" class="gall_item"><img src="images/page2_img4.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Sivamus at magna non nute </a></div>
            Rehoncus. Aliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laoreetet 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/bbig5.jpg" class="gall_item"><img src="images/page2_img5.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Kivamus at magna non nunj </a></div>
            Aliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laoreet 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/bbig6.jpg" class="gall_item"><img src="images/page2_img6.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Vivamus at magna non nunc </a></div>
            Rehoncus. Aliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laoreet 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
      <div class="clear sep__1"></div>
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/bbig7.jpg" class="gall_item"><img src="images/page2_img7.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Mivamus at magna non nunc </a></div>
            Lehoncus. Aliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laor 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/bbig8.jpg" class="gall_item"><img src="images/page2_img8.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Nivamus at magna non nunc </a></div>
            Rehoncus. Aliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laorees 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
      <div class="grid_4">
        <div class="gall_block">
          <div class="maxheight">
            <a href="images/bbig9.jpg" class="gall_item"><img src="images/page2_img9.jpg" alt=""></a>
            <div class="gall_bot">
            <div class="text1"><a href="#">Amusat magna non nunc </a></div>
            Oehoncus. Gliquam nibh antegestas id ictum a, commodo. Praesenterto faucibus maleada faucibusnec laeet metus id laore 
            <br>
            <a href="#" class="btn">more</a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--==============================
              footer
=================================-->

</body>
</html>


home/templates/home/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Stay tight, website is coming soon!</title>

<!--CSS-->
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
<link rel="stylesheet" href="{% static 'home/css/bootstrap-light.css' %}">
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
<!--/CSS-->

<!--JS-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="{% static 'home/js/jquery.plugin.js' %}"></script>
<script src="{% static 'home/js/jquery.countdown.js' %}"></script>
<script>
$(function () {
	$('#defaultCountdown').countdown({until: new Date(2016, 3-1, 25)}); 
	//Replace above date with your own, to find out more visit http://keith-wood.name/countdown.html
});
</script>
<!--/JS-->

</head>

<body>

<!--DARK OVERLAY-->
<div class="overlay"></div>
<!--/DARK OVERLAY-->

<!--WRAP-->
<div id="wrap">
	<!--CONTAINER-->
	<div class="container">
		<img src="{% static 'home/images/paperplane.png' %}" alt="Paper Plane" class="image-align" />
		<h1>
			<span>I am</span><br/>
			Reaching For <span class="yellow">The Moon.</span>
		</h1>
		<p>My site is currently <strong>under construction</strong> but I am working hard<br/> to create a new and fresh design.</p>
		<!--<div id="defaultCountdown"></div>-->
		<!--
		<form action="#">
			<input type="text" name="email" id="email" value="Subscribe to fond out when we are done">
			<input type="submit" value="GO!">
		</form>
		-->
		<!--<p class="copyright">Produly designed by <a href="https://herowp.com" target="_blank">HeroWP.com</a></p>-->
	</div>
	<!--/CONTAINER-->
</div>
<!--/WRAP-->

</body>
</html>